apiVersion: v1
kind: Service
metadata:
  name: nodeportservice
spec:
  type: NodePort
  selector:
    app: myreact
  ports:
    - protocol: TCP
      port: 80          # Service port (cluster madhe)
      targetPort: 5173  # Pod / container port
      nodePort: 30000   # Optional (range: 30000–32767)
